export const REQUEST_SESSION_USER = 'REQUEST_SESSION_USER'
export const FETCH_SESSION_USER_SUCCESS = 'FETCH_SESSION_USER_SUCCESS'
export const FETCH_SESSION_USER_FAIL = 'FETCH_SESSION_USER_FAIL'

export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS'
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS'
export const FETCH_ALL_USERS_FAIL = 'FETCH_ALL_USERS_FAIL'
