export const REQUEST_SESSION_USER = 'REQUEST_SESSION_USER'
export const FETCH_SESSION_USER_SUCCESS = 'FETCH_SESSION_USER_SUCCESS'
export const FETCH_SESSION_USER_FAIL = 'FETCH_SESSION_USER_FAIL'

export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS'
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS'
export const FETCH_ALL_USERS_FAIL = 'FETCH_ALL_USERS_FAIL'

export const REQUEST_PAGINATED_USERS = 'REQUEST_PAGINATED_USERS'
export const FETCH_PAGINATED_USERS_SUCCESS = 'FETCH_PAGINATED_USERS_SUCCESS'
export const FETCH_PAGINATED_USERS_FAIL = 'FETCH_PAGINATED_USERS_FAIL'

export const REVERT_PAGINATED_USERS_FULL = 'REVERT_PAGINATED_USERS_FULL'

export const REQUEST_SINGLE_USER = 'REQUEST_SINGLE_USER'
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_FAIL = 'FETCH_SINGLE_USER_FAIL'

export const REQUEST_SET_BASIC_INFO = 'REQUEST_SET_BASIC_INFORMATION'
export const SET_BASIC_INFO_SUCCESS = 'SET_BASIC_INFO_SUCCESS'
export const SET_BASIC_INFO_FAIL = 'SET_BASIC_INFO_FAIL'

export const REQUEST_SET_USER_AVATAR = 'REQUEST_SET_USER_AVATAR'
export const SET_USER_AVATAR_SUCCESS = 'SET_USER_AVATAR_SUCCESS'
export const SET_USER_AVATAR_FAIL = 'SET_USER_AVATAR_FAIL'

// Blockstack
export const REQUEST_BLOCKSTACK_DAPPS = 'REQUEST_BLOCKSTACK_DAPPS'
export const FETCH_BLOCKSTACK_DAPPS_SUCCESS = 'FETCH_BLOCKSTACK_DAPPS_SUCCESS'
export const FETCH_BLOCKSTACK_DAPPS_FAIL = 'FETCH_BLOCKSTACK_DAPPS_FAIL'

export const ADD_DAPPS_TO_LIST = 'ADD_DAPPS_TO_LIST'

// TODO: Delete this once users transition into radiks success
export const REQUEST_PROFILE_SEARCH = 'REQUEST_PROFILE_SEARCH'
export const FETCH_PROFILE_SEARCH_SUCCESS = 'FETCH_PROFILE_SEARCH_SUCCESS'
export const FETCH_PROFILE_SEARCH_FAIL = 'FETCH_PROFILE_SEARCH_FAIL'

// Shares
export const RESET_SHARES_LOADING = 'RESET_SHARES_LOADING'
export const REQUEST_USER_SHARES = 'REQUEST_USER_SHARES'
export const FETCH_USER_SHARES_SUCCESS = 'FETCH_USER_SHARES_SUCCESS'
export const FETCH_USER_SHARES_FAIL = 'FETCH_USER_SHARES_FAIL'

export const REQUEST_EDIT_SHARE = 'REQUEST_EDIT_SHARE'
export const EDIT_SHARE_SUCCESS = 'EDIT_SHARE_SUCCESS'
export const EDIT_SHARE_FAIL = 'EDIT_SHARE_FAIL'

export const REQUEST_CREATE_SHARE = 'REQUEST_CREATE_SHARE'
export const CREATE_SHARE_SUCCESS = 'CREATE_SHARE_SUCCESS'
export const CREATE_SHARE_FAIL = 'CREATE_SHARE_FAIL'

export const REQUEST_DELETE_SHARE = 'REQUEST_DELETE_SHARE'
export const DELETE_SHARE_SUCCESS = 'DELETE_SHARE_SUCCESS'
export const DELETE_SHARE_FAIL = 'DELETE_SHARE_FAIL'

// Comments
export const REQUEST_CREATE_COMMENT = 'REQUEST_CREATE_COMMENT'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'

export const REQUEST_SHARE_COMMENTS = 'REQUEST_SHARE_COMMENTS'
export const FETCH_SHARE_COMMENTS_SUCCESS = 'FETCH_SHARE_COMMENTS_SUCCESS'
export const FETCH_SHARE_COMMENTS_FAIL = 'FETCH_SHARE_COMMENTS_FAIL'

export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'

export const REQUEST_EDIT_COMMENT = 'REQUEST_EDIT_COMMENT'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL'

// Follow
export const REQUEST_FETCH_FOLLOW = 'REQUEST_FETCH_FOLLOW'
export const FETCH_FOLLOW_SUCCESS = 'FETCH_FOLLOW_SUCCESS'
export const FETCH_FOLLOW_FAIL = 'FETCH_FOLLOW_FAIL'

export const REQUEST_FOLLOW = 'REQUEST_FOLLOW'
export const SET_FOLLOW_SUCCESS = 'SET_FOLLOW_SUCCESS'
export const SET_FOLLOW_FAIL = 'SET_FOLLOW_FAIL'

export const REQUEST_UNFOLLOW = 'REQUEST_UNFOLLOW'
export const SET_UNFOLLOW_SUCCESS = 'SET_UNFOLLOW_SUCCESS'
export const SET_UNFOLLOW_FAIL = 'SET_UNFOLLOW_FAIL'

// Feed
export const REQUEST_FETCH_SHARE_FEEDS = 'REQUEST_FETCH_SHARE_FEEDS'
export const FETCH_SHARE_FEEDS_SUCCESS = 'FETCH_SHARE_FEEDS_SUCCESS'
export const FETCH_SHARE_FEEDS_FAIL = 'FETCH_SHARE_FEEDS_FAIL'

export const REQUEST_ADD_SHARE_FEEDS = 'REQUEST_ADD_SHARE_FEEDS'
export const REQUEST_DISPLAY_HIDDEN_SHARES = 'REQUEST_DISPLAY_HIDDEN_SHARES'
export const HANDLE_DETAIL_SHARE = 'HANDLE_DETAIL_SHARE'
export const REMOVE_DETAIL_SHARE = 'REMOVE_DETAIL_SHARE'
export const RESET_SHARES_FEED = 'RESET_SHARES_FEED'

// Vote
export const REQUEST_ADD_VOTE = 'REQUEST_ADD_VOTE'
export const ADD_VOTE_SUCCESS = 'ADD_VOTE_SUCCESS'
export const ADD_VOTE_FAIL = 'ADD_VOTE_FAIL'

export const REQUEST_REMOVE_VOTE = 'REQUEST_REMOVE_VOTE'
export const REMOVE_VOTE_SUCCESS = 'REMOVE_VOTE_SUCCESS'
export const REMOVE_VOTE_FAIL = 'REMOVE_VOTE_FAIL'
