export const REQUEST_SESSION_USER = 'REQUEST_SESSION_USER'
export const FETCH_SESSION_USER_SUCCESS = 'FETCH_SESSION_USER_SUCCESS'
export const FETCH_SESSION_USER_FAIL = 'FETCH_SESSION_USER_FAIL'

export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS'
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS'
export const FETCH_ALL_USERS_FAIL = 'FETCH_ALL_USERS_FAIL'

// Blockstack
export const REQUEST_BLOCKSTACK_APPS = 'REQUEST_BLOCKSTACK_APPS'
export const FETCH_BLOCKSTACK_APPS_SUCCESS = 'FETCH_BLOCKSTACK_APPS_SUCCESS'
export const FETCH_BLOCKSTACK_APPS_FAIL = 'FETCH_BLOCKSTACK_APPS_FAIL'

export const REQUEST_PROFILE_SEARCH = 'REQUEST_PROFILE_SEARCH'
export const FETCH_PROFILE_SEARCH_SUCCESS = 'FETCH_PROFILE_SEARCH_SUCCESS'
export const FETCH_PROFILE_SEARCH_FAIL = 'FETCH_PROFILE_SEARCH_FAIL'

export const REQUEST_USER_INTRO = 'REQUEST_USER_INTRO'
export const FETCH_USER_INTRO_SUCCESS = 'FETCH_USER_INTRO_SUCCESS'
export const FETCH_USER_INTRO_FAIL = 'FETCH_USER_INTRO_FAIL'

// Shares
export const REQUEST_USER_SHARES = 'REQUEST_USER_SHARES'
export const FETCH_USER_SHARES_SUCCESS = 'FETCH_USER_SHARES_SUCCESS'
export const FETCH_USER_SHARES_FAIL = 'FETCH_USER_SHARES_FAIL'

export const REQUEST_CREATE_SHARE = 'REQUEST_SHARE_CREATE'
export const CREATE_SHARE_SUCCESS = 'CREATE_SHARE_SUCCESS'
export const CREATE_SHARE_FAIL = 'CREATE_SHARE_FAIL'
